export const product = [
    {
        availability: null,
        price: 200,
        name: "International SmileVoice ONLY 23",
        allowance: "International SmileVoice ONLY 23",
        validity: "3",
        code: "508",
    },
    {
        availability: null,
        price: 300,
        name: " 1GB FlexiDaily",
        allowance: " 1GB FlexiDaily",
        validity: "1",
        code: "624",
    },
    {
        availability: null,
        price: 500,
        name: " 2.5GB FlexiDaily",
        allowance: " 2.5GB FlexiDaily",
        validity: "2",
        code: "625",
    },
    {
        availability: null,
        price: 500,
        name: "1GB FlexiWeekly",
        allowance: "1GB FlexiWeekly",
        validity: "7",
        code: "626",
    },
    {
        availability: null,
        price: 500,
        name: "International SmileVoice ONLY 60",
        allowance: "International SmileVoice ONLY 60",
        validity: "7",
        code: "509",
    },
    {
        availability: null,
        price: 510,
        name: "SmileVoice ONLY 65",
        allowance: "SmileVoice ONLY 65",
        validity: "30",
        code: "516",
    },
    {
        availability: null,
        price: 1000,
        name: "1.5GB Bigga",
        allowance: "1.5GB Bigga",
        validity: "30",
        code: "606",
    },
    {
        availability: null,
        price: 1000,
        name: " 2GB FlexiWeekly ",
        allowance: " 2GB FlexiWeekly ",
        validity: "7",
        code: "627",
    },
    {
        availability: null,
        price: 1000,
        name: "International SmileVoice ONLY 125",
        allowance: "International SmileVoice ONLY 125",
        validity: "30",
        code: "510",
    },
    {
        availability: null,
        price: 1020,
        name: "SmileVoice ONLY 135",
        allowance: "SmileVoice ONLY 135",
        validity: "30",
        code: "517",
    },
    {
        availability: null,
        price: 1020,
        name: "2GB MidNite",
        allowance: "2GB MidNite",
        validity: "7",
        code: "413",
    },
    {
        availability: null,
        price: 1200,
        name: "2GB Bigga",
        allowance: "2GB Bigga",
        validity: "30",
        code: "607",
    },
    {
        availability: null,
        price: 1500,
        name: "3GB Bigga",
        allowance: "3GB Bigga",
        validity: "30",
        code: "608",
    },
    {
        availability: null,
        price: 1500,
        name: " 6GB FlexiWeekly ",
        allowance: " 6GB FlexiWeekly ",
        validity: "7",
        code: "628",
    },
    {
        availability: null,
        price: 1500,
        name: "SmileVoice ONLY 150",
        allowance: "SmileVoice ONLY 150",
        validity: "60",
        code: "698",
    },
    {
        availability: null,
        price: 1530,
        name: "3GB MidNite",
        allowance: "3GB MidNite",
        validity: "7",
        code: "414",
    },
    {
        availability: null,
        price: 1530,
        name: "3GB Weekend ONLY",
        allowance: "3GB Weekend ONLY",
        validity: "3",
        code: "415",
    },
    {
        availability: null,
        price: 2000,
        name: "5GB Bigga",
        allowance: "5GB Bigga",
        validity: "30",
        code: "620",
    },
    {
        availability: null,
        price: 2000,
        name: "SmileVoice ONLY 175",
        allowance: "SmileVoice ONLY 175",
        validity: "90",
        code: "700",
    },
    {
        availability: null,
        price: 2500,
        name: "6.5GB Bigga",
        allowance: "6.5GB Bigga",
        validity: "30",
        code: "609",
    },
    {
        availability: null,
        price: 3000,
        name: "10GB Bigga",
        allowance: "10GB Bigga",
        validity: "30",
        code: "722",
    },
    {
        availability: null,
        price: 3070,
        name: "SmileVoice ONLY 430",
        allowance: "SmileVoice ONLY 430",
        validity: "30",
        code: "518",
    },
    {
        availability: null,
        price: 4000,
        name: "SmileVoice ONLY 450",
        allowance: "SmileVoice ONLY 450",
        validity: "60",
        code: "699",
    },
    {
        availability: null,
        price: 4000,
        name: "15GB Bigga",
        allowance: "15GB Bigga",
        validity: "30",
        code: "723",
    },
    {
        availability: null,
        price: 5000,
        name: "Smile Voice ONLY 500",
        allowance: "Smile Voice ONLY 500",
        validity: "90",
        code: "701",
    },
    {
        availability: null,
        price: 5000,
        name: "20GB Bigga",
        allowance: "20GB Bigga",
        validity: "30",
        code: "724",
    },
    {
        availability: null,
        price: 6000,
        name: "25GB Bigga",
        allowance: "25GB Bigga",
        validity: "30",
        code: "725",
    },
    {
        availability: null,
        price: 8000,
        name: "30GB Bigga",
        allowance: "30GB Bigga",
        validity: "30",
        code: "615",
    },
    {
        availability: null,
        price: 9000,
        name: "15GB 365",
        allowance: "15GB 365",
        validity: "365",
        code: "687",
    },
    {
        availability: null,
        price: 10000,
        name: "40GB Bigga",
        allowance: "40GB Bigga",
        validity: "30",
        code: "616",
    },
    {
        availability: null,
        price: 12000,
        name: "UnlimitedLite",
        allowance: "UnlimitedLite",
        validity: "30",
        code: "730",
    },
    {
        availability: null,
        price: 13500,
        name: "60GB Bigga",
        allowance: "60GB Bigga",
        validity: "30",
        code: "617",
    },
    {
        availability: null,
        price: 15000,
        name: "75GB Bigga",
        allowance: "75GB Bigga",
        validity: "30",
        code: "618",
    },
    {
        availability: null,
        price: 18000,
        name: "100GB Bigga",
        allowance: "100GB Bigga",
        validity: "30",
        code: "619",
    },
    {
        availability: null,
        price: 18000,
        name: "UnlimitedEssential",
        allowance: "UnlimitedEssential",
        validity: "30",
        code: "729",
    },
    {
        availability: null,
        price: 19000,
        name: "35GB 365",
        allowance: "35GB 365",
        validity: "365",
        code: "688",
    },
    {
        availability: null,
        price: 19800,
        name: "130GB Bigga",
        allowance: "130GB Bigga",
        validity: "30",
        code: "668",
    },
    {
        availability: null,
        price: 20000,
        name: "90GB Jumbo",
        allowance: "90GB Jumbo",
        validity: "60",
        code: "665",
    },
    {
        availability: null,
        price: 25000,
        name: "Freedom 3Mbps",
        allowance: "Freedom 3Mbps",
        validity: "30",
        code: "726",
    },
    {
        availability: null,
        price: 30000,
        name: "Freedom 6Mbps",
        allowance: "Freedom 6Mbps",
        validity: "30",
        code: "727",
    },
    {
        availability: null,
        price: 32000,
        name: "70GB 365",
        allowance: "70GB 365",
        validity: "365",
        code: "689",
    },
    {
        availability: null,
        price: 34000,
        name: "160GB Jumbo",
        allowance: "160GB Jumbo",
        validity: "90",
        code: "666",
    },
    {
        availability: null,
        price: 40000,
        name: "200GB Jumbo",
        allowance: "200GB Jumbo",
        validity: "120",
        code: "667",
    },
    {
        availability: null,
        price: 40000,
        name: "Freedom BestEffort",
        allowance: "Freedom BestEffort",
        validity: "30",
        code: "728",
    },
    {
        availability: null,
        price: 50000,
        name: "125GB 365",
        allowance: "125GB 365",
        validity: "365",
        code: "664",
    },
    {
        availability: null,
        price: 50000,
        name: "400GB Jumbo",
        allowance: "400GB Jumbo",
        validity: "180",
        code: "721",
    },
    {
        availability: null,
        price: 70000,
        name: "200GB 365",
        allowance: "200GB 365",
        validity: "365",
        code: "604",
    },
    {
        availability: null,
        price: 100000,
        name: "500GB 365",
        allowance: "500GB 365",
        validity: "365",
        code: "673",
    },
    {
        availability: null,
        price: 120000,
        name: "1TB 365",
        allowance: "1TB 365",
        validity: "365",
        code: "674",
    },
];
